.travis.yml
Cache the IsolatedGalaxy dataset.
=> Cache IsolatedGalaxy on travis.

src/python/examples/cooling_cell.py, src/python/examples/cooling_rate.py, src/python/examples/freefall.py, src/python/examples/run_from_yt.py
Some temp commits to debug travis issues.
=> fix testing

README.md, doc/Makefile, doc/source/Help.rst
This updates the README with badges and more description of the code. I also went through and capitalized all mentions of Grackle.
=> Update README and small doc format fixes

src/python/pygrackle/utilities/convenience.py
Following issue #30  add a comment for the units in `setup_fluid_container`
=> Add comment about units

src/clib/Make.mach.summit
Included a Makefile to use on ORNL Summit.
Need to load module hdf5
=> added makefile for ORNL Summit

doc/source/Integration.rst, src/clib/grackle.h, src/clib/grackle_macros.h, src/clib/initialize_chemistry_data.c, src/clib/initialize_cloudy_data.c, src/example/cxx_example.C
Implement #35 
Here is the method to free the memory.
=> Add free method

src/example/c_example.c
=> Fix memory allocation in c example

.circleci/config.yml, src/python/setup.py
This should get testing back on track.
=> Update python versions and prevent use of latest matplotlib.

doc/source/Installation.rst
This adds instructions for how to initialize the submodule containing the cooling and testing files.
Resolves Issue #76.
=> Add instructions for how to initialize data submodule.

src/python/pygrackle/yt_fields.py, src/python/tests/test_chemistry.py, src/python/tests/test_code_examples.py, src/python/tests/test_examples.py, src/python/tests/test_primordial.py
This updates some of the python tests for yt deprecations and converts string to fstrings for readability.
=> python and yt updates

doc/source/RateFunctions.rst, doc/source/index.rst
Issue #89 
Added documentation for the new rate coefficient functions. This explains their inputs/outputs, how to use each type of function and the differences between them. I have also provided a few simple examples to show how these functions can be used. 
This has been added as a new .rst file, claiming its own section within the documentation. If I have missed anything obvious feel free to let me know!
Ewan
=> Updated Documentation

doc/source/Parameters.rst, src/clib/solve_rate_cool_g.F
With @AndreaIncatasciato's permission, I've taken on PR #72 to see if we can get it merged. Since it's been a while since this was issued, I did a rebase on master but I did not want to overwrite what was in Andrea's fork, so I'm issuing this as a new PR.
@gregbryan, I believe the only unresolved issue was whether to introduce a new runtime parameter to enable this optionally. Do you have any thoughts on that? I'm happy to do it if the older behavior is worth preserving.
=> New h2selfshielding (reissue of PR #72)

doc/source/Integration.rst
This resolves Issue #69. I've added more discussion about density fields in general and the nuances of the electron density field.
=> Add clarification to docs on electron density.

src/python/pygrackle/grackle_defs.pxd, src/python/pygrackle/grackle_wrapper.pyx
This PR includes some self-explanatory changes to PyGrackle. These changes include:
- fixing a memory leak
- reducing some code duplication
=> Pygrackle tweaks

doc/source/Integration.rst
This adds mention of a new example code (added in PR #170) to the documentation.
=> Add mention of c local example to docs.

.circleci/config.yml, doc/source/conf.py, doc/source/requirements.txt
Resolves #219 
In slightly more detail, this PR changes the website theme to use the readthedocs theme.
=> Address GH #219 adopt rtd theme

src/include/grackle_fortran_interface.def
This parameter was originally put in the wrong place (by me).
=> Move parameter to correct place in fortran interface.

.circleci/config.yml, doc/source/Testing.rst, pyproject.toml
This PR adds instructions for locally running the corelib tests in order to resolves #281
=> Add instructions for running the corelib tests

doc/source/Testing.rst, doc/source/testing_snippets/generate.rst
I meant to submit this last week. This PR adds more details about running the pygrackle test suite
=> Pygrackle test instruction tweaks

doc/source/Parameters.rst
Three extremely minor formatting fixes.
=> Fix spacing issues in docs.

.github/workflows/wheels.yml
This is pretty self-explanatory
=> Modify GHA to stop trying to upload to TestPyPI after every PR
