grackle-project/grackle

src/clib/calculate_cooling_time.c
src/clib/grackle_chemistry_data.h
src/clib/initialize_chemistry_data.c
src/clib/solve_chemistry.c
src/clib/update_UVbackground_rates.c

Strictly speaking, `update_UVbackground_rates` is not thread-safe as it updates global variables in the `chemistry_data_storage` struct. This is not a problem for Grackle's OpenMP implementation, but could be an issue for codes that have multiple threads calling `calculate_cooling_time` or `solve_chemistry`.
This PR makes use of a temporary struct that holds only the interpolated photo-rates and passes those to `calculate_cooling_time` and `solve_chemistry`.

[bugfix] Update UVB rates using a local struct for thread-safety

---

src/clib/update_UVbackground_rates.c

The older value (1.13e8) is valid for an unnormalized flat incident radiation flux in units of erg cm^-2 s^-1 Hz^-1 (see Abel et al., 1997).
1.38e-12, instead, is valid for a flat intensity in units of 10^-21 erg cm^-2 s^-1 Hz^-1 sr^-1.
Since the LWbackground_intensity is expressed with these units, the latter value should be used.

k31 changed - H2 photodissociation rate

---

src/clib/initialize_chemistry_data.c

This moves the printout of the parameter setting to the end of `_initialize_chemistry_data` so that changed made to the UV background parameters that happens in `initialize_UVbackground_data` are properly reflected. Before this, they will always read as their default values of -99999.

Change order or print statements to reflect change in UVB parameters.

---

src/clib/Make.mach.tacc-stampede-gnu
src/clib/Make.mach.tacc-stampede-intel
src/python/pygrackle/grackle_wrapper.pyx
src/python/setup.py

This pull request includes includes fixes to issues with building grackle on stampede2. There are 2 main sets of changes.
First, I updated the compile settings in the tacc-stampede-intel and tacc-stampede-gnu build settings. I have originally made these modifications on commit 6ae37b2b1fc1957aeb6020a85a3b1f23ee14f489 and on that commit I confirmed that grackle will now successfully compile using both compilers.  After rebasing the branch I subsequently reconfirmed that grackle builds with the intel compiler (but have not checked again with the intel compilers). 
As a brief aside, the Stampede2 user guide recommends a few different sets of compiler flags to be used with the intel compiler based on which of the 2 types of compute nodes are used. They suggest two flexible options: only use …

Updates for Stampede Builds

---

src/example/Makefile

For gfortran version 9.2.1, an optimization level of -O2 or higher leads to weird optimizations of the string that holds the path to the grackle input file in the fortran code example. This causes one of the tests to fail.
To remedy this issue I have hardcoded in the -O1 optimization flag into the portion of the Makefile responsible for compiling this test program in order to overwrite whatever optimization flag was specified for compiling the grackle library.
Let me know if there is a better way to resolve this issue.

Minor tweak to allow tests to pass with gfortran

---

.circleci/config.yml

This is a stopgap to get the docs building again. Unclear if it will be necessary to change things or if there is a bug in newer versions of sphinx.

Require older sphinx version.

---

doc/source/Parameters.rst

Hi,
The current table goes up to a density of 10^4 atom / cm3. Here is a table going up to a density of 10^10 atom / cm3.
Below, you will find a few plots in order to compare the different tables.
The cooling length for the new table:
The cooling length for the old table (extrapolated above 10^4 atom/cm3):
The cooling length for a reproduction of the old table done with my script and a recent version of Cloudy:
The relative difference between the cooling length of the old and new table `(L_old - L_new) / L_old`:
We can see that it impacts mostly the dense gas heated by supernovae and slightly shift the equilibrium.
By the way, I have also updated the documentation with a comment about the new table and with a fix on the unit of density (I removed an extra `-`).

Add high density table

---

src/clib/calc_temp1d_cloudy_g.F
src/python/tests/test_chemistry.py

This PR is meant to address Issue #67. I also introduced a simple test to make sure that introducing a metal density field increases the mmw, when `primordial_chemistry=0`.
I have included the updated answer tests here since I'm not sure what the protocol is for updating the submodule:
- [cooling_cell.zip](https://github.com/grackle-project/grackle/files/5876903/cooling_cell.zip)
- [cooling_rate.pc0.zip](https://github.com/grackle-project/grackle/files/5876904/cooling_rate.pc0.zip)
I considered generalizing this test to also include the other `primordial_chemistry` values, but that involves tweaking both
- `FluidContainer`'s `calculate_mean_molecular_weight` method to account for the presence of metals when the `"energy"` field is uniformly zero
-  and `setup_fluid_container` to ensure …

Mmw bugfix

---

src/python/pygrackle/grackle_wrapper.pyx

Previously the underlying `chemistry_data` struct was invalidated if the bytearray used to specify the `grackle_data_path` was garbage collected. The cause of this is discussed at the end of [this section of the Cython documentation](https://cython.readthedocs.io/en/latest/src/tutorial/strings.html#passing-byte-strings) 
I have a couple other minor tweaks that may be worth introducing to Grackle. But those are probably worth discussing offline, before I put them together in a PR.

Fixing lifetime issue for grackle_data_path in the Cython Grackle wrapper

---

src/clib/Make.mach.nasa-aitken-rome
src/clib/Make.mach.nasa-pleiades

Updated the modules and paths for the Pleiades machine file, created a new machine file for the Aitken Rome nodes (https://www.nas.nasa.gov/hecc/support/kb/preparing-to-run-on-aitken-rome-nodes_657.html). I couldn't get the `MACHINE_NOTES` to work (?!) so wound up leaving it as an empty string to get it to compile.

updating makefiles for NASA's HECC machines

---

.circleci/config.yml

This should fix the circleci build issues.

Use apt instead of apt-get in circleci script.

---

src/python/examples/freefall.py

In the pygrackle example file freefall.py velocity_units were defined with a factor of a_value. This was not consistent with the units being input as proper coordinates. This factor of a_value is now removed so all unit definitions are consistent.

Fix velocity_units in freefall.py

---

src/python/examples/cooling_cell.py
src/python/examples/cooling_rate.py
src/python/examples/freefall.py

PR #92 fixed the velocity units in the freefall python script, but the same issue existed in a couple others. I've changed those as well now, but decided to add some code that does either to make it clearer to the user what should be done in either case.

add proper and comoving velocity units to python scripts

---

.circleci/config.yml
src/python/setup.py

This does a few things to update and simplify the testing:
- limit to a single python version. This should minimize version-specific differences in testing answers.
- use the oldest version of python supported by current yt. This is a sensible way to set the oldest allowed version.
- update circleci docker images
- ~~get rid of numbered cache versioning since we cannot actually return to earlier versions.~~
- remove dependencies cache entirely as dependencies take about 20s to install

testing and python packaging updates

---

.circleci/config.yml
.gitignore
doc/source/Integration.rst
doc/source/Python.rst
doc/source/Reference.rst
src/clib/Make.config.objects
src/clib/Makefile
src/clib/grackle.h
src/clib/grackle_types.h
src/clib/initialize_chemistry_data.c
src/python/pygrackle/grackle_defs.pxd
src/python/pygrackle/grackle_wrapper.pyx
src/python/setup.py
src/python/tests/test_get_grackle_version.py

This PR adds the ability to query the Grackle Version to the public API. This feature is useful for external simulations that want to compare grackle versions before and after a restart.
If you would prefer not to expand the public API, just let me know and we can close this PR. In hindsight, it may have been better to gauge interest in this feature before I created this PR (I was encouraged by the fact that the version information was already encoded within the library - I was just making it more easily accessible).
Overview
-------------
This PR consists of the following changes:
- I introduced the following struct declaration to `grackle_types.h`:
```c++
typedef struct { const char* version; const char* branch; const char* revision; } grackle_version;
```
- I replaced the …

Add ability to query the Grackle Version

---

src/clib/Make.config.targets

This addresses Issue #113, which documented a compilation error that occurred when Grackle is downloaded without the Git metadata. The errors occurred because `make show-version` produced output with an unexpected format.

[Bugfix] Issue #113 - provide sensible version info without git

---

src/clib/Makefile
src/clib/grackle.h

I was getting a compile error on various systems saying, "function declaration isn't a prototype". This seems to come from ambiguities in C around functions that accept no arguments.

Change get_grackle_version to explicitly accept zero arguments.

---

src/clib/index_helper.c
src/clib/index_helper.h

I'm not sure why the new `_inner_range` function wasn't being included in the library, but I needed to move it from the header file to the .c file. When grackle was linked from enzo, it raised a linking error saying that `_inner_range` was undefined. I confirmed that it was not present in the library. I am using GCC v9.4.0.
```console
$ nm -D .libs/libgrackle.so
[...]
U _inner_range
[...]
```

Changing _inner_range to `static inline` to avoid undefined reference

---

.circleci/config.yml
src/python/pygrackle/yt_fields.py

This updates the python version used on circleci to 3.8, which is now the minimum supported version by yt.
Edit, the "thermal_energy" field was deprecated and now removed in yt in favor of "specific_thermal_energy". This updates pygrackle for that change.

Increment python testing version

---

doc/source/Integration.rst
src/clib/solve_rate_cool_g.F

This resolves Issue #48. As per the discussion on the issue, I have removed the arbitrary ceiling on the metal density and added a warning for when the metal density exceeds the total density. I have also expanded and updated the discussion of units in the docs. Separately, I fixed a few formatting issues that I ran into and that popped up as a result of my changes.
@mabruzzo, you reported this issue originally. Does this look like a satisfactory fix?

Expand units documentation and remove ceiling on metal density

---

doc/source/Installation.rst
src/clib/Makefile

This closes issue #14. I've added a warning to both the docs and to be printed at compile time.

Add warnings about compiling in single precision.

---

doc/source/Parameters.rst
src/clib/grackle_chemistry_data.h
src/clib/grackle_fortran_interface.def
src/clib/initialize_chemistry_data.c
src/clib/set_default_chemistry_parameters.c
src/clib/solve_chemistry.c
src/clib/solve_rate_cool_g.F

This resolves Issue #112.
The iteration limit in `solve_chemistry` is currently controlled by the constant, `itmax`, defined within `solve_rate_cool`. This converts it to a runtime parameters so the code doesn't need to be recompiled to increase it. I have also added a new parameter `exit_after_iterations_exceeded` to control behavior when the iteration limit is exceeded. For backward compatibility, I have set the default to be 0, i.e., the current behavior of printing a warning and carrying on. If set to 1, the code will exit immediately with a return value of failure.
I've tested this with some of the example executables and it seems to work as desired. I've also added some documentation for these parameters, including an appeal to report situation where increasing itmax doesn't help.

Convert iteration limit to a runtime parameter

---

.circleci/config.yml
doc/source/Integration.rst
doc/source/RateFunctions.rst
doc/source/Reference.rst

Grackle has required a version of sphinx prior to 3.0 to build warning/error free. This fixes the various issues that popped up after sphinx 3.0 and should now allow the docs to be compiled without warnings or errors on the latest version of sphinx. I had to restructure the section on reaction rates to avoid duplicate definitions, but the content is largely the same. There were a handful of other syntax issues as well.

documentation fixes for later sphinx versions

---

src/clib/Make.config.assemble
src/clib/grackle_fortran_types.def
src/clib/initialize_cloudy_data.c
src/clib/phys_const.def

This fixes an issues reported on slack where intel compilers were picking up a duplicate definition of CONFIG_BFLOAT. This was introduced in PR #118 when this define was added to a header file but not removed from the compile flags. I also added a missing header that intel asked for.

Remove duplicate precision definition during compile

---

.circleci/config.yml
src/python/tests/test_chemistry_struct_synched.py

This PR introduces a test to explicitly check that there is a 1-to-1 mapping between the parameters that can be configured through dynamic API functions (introduced in PR #130) and the fields in the ``chemistry_data`` struct. 
The test is primarily intended to ensure that these don't fall out of sync when new parameters get added to ``chemistry_data``.
This test makes use of a program called ``castxml`` (https://github.com/CastXML/CastXML). This is a program (built on top of ``LLVM``/``clang``) that parses C++ code and outputs the syntax tree of all of all C++ structs/classes (their fields and methods), namespaces, function declarations, and global variables.
The new test executes ``castxml`` on the header containing the declaration of the ``chemistry_data`` struct and parses the output …

Add test of synchronization between ``chemistry_data`` and dynamic API.

---

src/clib/grackle.h

Using GCC 11, compiling Enzo will fail unless `grackle.h` includes `cstddef`. Including this header does not seem to prevent older versions of GCC (like 6.4) from compiling Enzo.

Need cstddef or size_t undefined

---

doc/source/Reference.rst
src/clib/dynamic_api.c
src/clib/grackle.h

Introduce the ``grackle_num_params`` function to let users query the number of parameters of a given type that are stored in ``chemistry_data``.
When I first implemented the dynamic-api, I omitted this function because I didn't anticipate it being particularly useful and I wanted to avoid expanding the API by too much.
- Indeed, I didn't really feel like I needed this function while refactoring Grackle's python bindings.
- However, it turns out that this functionallity is VERY useful when using the dynamic-api to write code in a statically typed language like C/C++ (while trying to minimize the definition of global variables). It's especially useful to know the number of parameters of a given type, before iterating over the parameters of that type during serialization.
The new function …

Add ability to query the number of parameters of a given type

---

doc/source/Integration.rst
doc/source/Reference.rst
src/clib/Make.config.assemble
src/clib/Makefile
src/clib/grackle.h
src/clib/initialize_chemistry_data.c
src/clib/set_default_chemistry_parameters.c
src/example/cxx_example.C
src/example/cxx_grid_example.C
src/python/pygrackle/grackle_defs.pxd
src/python/pygrackle/grackle_wrapper.pyx

This addresses the changes highlighted in Issue #138. Specifically, we have renamed some functions to drop the leading underscore in the names.
As discussed in that issue, I have renamed the following functions:
- `_set_default_chemistry_parameters` -> `local_initialize_chemistry_parameters`
- `_initialize_chemistry_data` -> `local_initialize_chemistry_data`
I also renamed `_free_chemistry_data` to be called `free_chemistry_data`. However, there's a piece of me that wonders whether it should really be called `local_free_chemistry_data`. **What do you think about that?**
I had to make a few tweaks to the python wrapper and the code examples to make use of the new function names.
I also updated some of the documentation that relates to these functions. While doing that, I tried to add …

Deprecating functions

---

doc/source/Reference.rst
src/clib/dynamic_api.c
src/clib/grackle.h
src/python/pygrackle/grackle_defs.pxd
src/python/pygrackle/grackle_wrapper.pyx

This lets us drop the ``#include <stddef.h>`` line from the public header file. This is not a super important change. I don't think this is a necessary change, but it conforms with previous conventions (that avoid including c standard library headers). Feel free to ignore this.

Replaced ``size_t`` with ``unsigned int`` in the dynamic api functions.

---

.readthedocs.yml

This issue is documented here: https://github.com/readthedocs/readthedocs.org/issues/10290
@jwise77 introduced the exact same change to Enzo as part of enzo-project/enzo-dev#210
Another option is just to wait for the ReadTheDocs people to fix this problem. I'm sure this problem will eventually be resolved on its own (since it affects everybody that uses the default-legacy build options)

Specifying an OS for RTDs to avoid an SSL issue with the newest urllib version

---

src/python/pygrackle/__init__.py
src/python/setup.py

This resolves Issue #111, giving pygrackle a stable version number that we can track properly moving forward from the next release of Grackle.

Update pygrackle version to 1.0.0 and add metadata.

---

src/clib/grackle_chemistry_data.h
src/clib/grackle_chemistry_data_fields.def
src/clib/initialize_chemistry_data.c
src/python/tests/test_chemistry_struct_synched.py

Previously, ``omp_nthreads`` was conditionally included as a field when Grackle was compiled with ``OPENMP``. This replaces PR #145.

Modified the ``chemistry_data`` struct so that the ``omp_nthreads`` is always a field

---

.circleci/config.yml
.gitmodules
CONTRIBUTING.rst
README.md

This reflects the change I just made in renaming the primary branch from master to main. I have also changed the primary branch name for the `grackle_data_files` repo accordingly. This will finish Issue #129.

Update branch name references from master to main

---

doc/source/Parameters.rst

This adds a warning about using the self-shielding cooling tables, following [Issue #7](https://github.com/grackle-project/grackle_data_files/issues/7) of [grackle_data_files](https://github.com/grackle-project/grackle_data_files/).

Add warning about self-shielding cooling tables.

---

src/clib/grackle.h

I had forgotten that the ``inline`` specifier works differently in C and C++ while writing PR #139. When I wrote that PR, I had assumed the C++ semantics apply everywhere. It turns out that to achieve the desired behavior, we need to label the functions as ``static inline`` (this works in both C and C++).
I had realized this was a problem while doing something totally unrelated in PR #153

Bugfix: making inline legacy internal grackle functions work in C codes

---

src/clib/initialize_chemistry_data.c

This adds the expected return value to the end of `local_free_chemistry_data`.

Add missing return value.

---

src/clib/initialize_chemistry_data.c

I'm compiling grackle on a Mac M1 with clang v14, and due to strict compilation standards, I was running into a compilation issue when trying to `make` inside `src/clib`. The specific error shown in `out.compile` is as follows: `initialize_chemistry_data.c:290:7: error: call to undeclared function 'local_free_chemistry_data'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]`. This seems to be a clang-specific issue.
I therefore initialized the variable near the top of the file and grackle is able to compile without issues.

initializing local_free_chemistry_data

---

src/clib/initialize_rates.c

I just fixed 2 typos and found a spot where we could use a stack-allocated array rather than a heap-allocated array

Minor tweaks to `initialize_rates.c` of little importance.

---

src/clib/initialize_UVbackground_data.c
src/clib/initialize_chemistry_data.c
src/clib/initialize_cloudy_data.c

Dangling uninitialized pointers and arrays in data structures caused issues for me when using local (threadsafe) function calls. The issues range from causing segfaults to memory leaks to arithmetic exceptions to randomly massively slowing down the code by computing random junk on randomly large arrays which shouldn't exist in the first place.
This PR initializes all structs explicitly, and the issues have vanished for me.
Only thing I'm not 100% sure about is, as I wrote on slack already, is that you define the `cloudy_data struct` as:
```
typedef struct
{
...
// Dataset parameter values.
double **grid_parameters;
...
} cloudy_data;
```
but you initialize grid_parameters as
```
int initialize_cloudy_data(chemistry_data *my_chemistry,
chemistry_data_storage *my_rates,
cloudy_data …
```

explicitly initialize all struct members to solve plethora of issues

---

src/clib/initialize_chemistry_data.c

Removed a couple unnecessary mallocs. These pointers both get a second malloc later when they are setup inside `add_rection_rate`. They are also initialized to NULL previously.

Fix memory leak

---

src/clib/grackle_chemistry_data.h
src/clib/initialize_cloudy_data.c

Previously, `cloudy_data.grid_dimension` and `cloudy_data.grid_parameters` were assigned heap-allocated arrays of a fixed size (set by the maximum size of the `CLOUDY_MAX_DIMENSION`).
This changeset:
1. renames the `CLOUDY_MAX_DIMENSION` macro so it is now called `GRACKLE_CLOUDY_TABLE_MAX_DIMENSION` and moves it to the `grackle_chemistry_data.h` header.
2. changes the types of the `cloudy_data.grid_dimension` and `cloudy_data.grid_parameters` struct-members so that they are now arrays with ``GRACKLE_CLOUDY_TABLE_MAX_DIMENSION` entries.
3. simplifies the implementation of `initialize_cloudy_data`. 2 of the allocations are no longer necessary and the initialization of the array-values are moved into `initialize_empty_cloudy_data_struct`. **(This was the main motivation for this PR)**
4. …

Refactor the `cloudy_data` struct so that the `grid_{dimension,parameters}` members are fixed-size arrays

---

src/example/Makefile
src/example/c_example.c
src/example/c_local_example.c
src/python/tests/test_code_examples.py

Inconsistencies in c_example.c lead to using both the default and user-defined chemistry_data structs. I have changed this such that all structs are defined explicitly in the example. The local_ version of initialize_chemistry_data is now used.

Fixed inconsistencies in c_example

---

src/python/pygrackle/fluid_container.py
src/python/pygrackle/grackle_defs.pxd
src/python/pygrackle/grackle_wrapper.pyx

Following an issue reported on the mailing list, this adds some fields that were missing from the pygrackle interface. I also did a little reordering for consistency between the various places these are defined.

Add missing fields to pygrackle.

---

src/python/pygrackle/fluid_container.py

The contribution of H in HDI should be 1/3, not 1/2. Also, the species for primordial_chemistry = 3 were not included in the mean molecular weight.

Fix pygrackle H number density and mean molecular weight calculations

---

src/clib/grackle_chemistry_data.h
src/clib/grackle_types.h
src/python/tests/test_chemistry_struct_synched.py

Prior to this PR, all types that alias structs alias anonymous structs. This is totally fine, but it prevents users from forward declaring types.
In this PR, we make:
- `chemistry_data` an alias for `struct chemistry_data`
- `code_units` an alias for `struct code_units`
- `chemistry_data_storage` an alias for `struct chemistry_data_storage`
- `grackle_field_data` an alias for `struct grackle_field_data`
By doing this, downstream codes can now forward declare types like `struct chemistry_data`, regardless of whether grackle is being linked in the current build.
- this is extremely useful for reducing pre-processor ifdef statements
- In Enzo-E, I'm looking to use this feature so that we don't have to rebuild the entire program if we decide to rebuild with/without linking against Grackle

Make public types refer to named structs

---

src/example/Makefile

This adds c_local_example to the list of executables to remove with make clean.

Add example to make clean list.

---

src/clib/grackle_chemistry_data.h
src/clib/grackle_types.h

Overview
--------
This commit (mostly)[^1] reverts PR #179. When I originally wrote #179 I didn't give the side effects a ton of thought.
I actually don't think the "problem" is a huge deal. But I do think that we should probably make this reversion quickly before people start depending on the feature added by #179.
Refresher
---------
As a quick refresher about PR #179:
- Previously we declared the types `chemistry_data`, `chemistry_data_storage`, `code_units`, and `grackle_field_data` as aliases of anonymous structs.
- In that PR, I modified the code so that those types are aliases of `struct chemistry_data`, `struct chemistry_data_storage`, `struct code_units`, and `struct grackle_field_data`.
- That PR was submitted with the express purpose of allowing downstream applications to …

Revert PR #179

---

doc/source/Integration.rst
src/clib/Make.config.objects
src/clib/calculate_cooling_time.c
src/clib/solve_chemistry.c
src/clib/utils.c
src/clib/utils.h

The `grid_dx` field is only needed for a subset of grackle operations and it sometimes doesn't make sense for a downstream application to properly set the value (e.g. where cells are not perfect cubes or if the code isn't grid-based).
I also tweaked the documentation to recommend that downstream applications set `grackle_field_data.grid_dx` to something `-1` in cases where it's not applicable (if the value is not initialized at all, the new error check might not work...)
As part of this commit, I actually factored the error-check out into it's own function (as well as another related check) in order to make sure that we apply the same test in both the `calculate_cooling_time` and `solve_chemistry` functions.
I placed that function inside of a newly created file called `utils.c`. I think …

Add error-check on `grackle_field_data.grid_dx`

---

src/clib/solve_chemistry.c
src/python/pygrackle/grackle_wrapper.pyx

Adding a missing include-directive (that was forgotten in PR #190). This also sets `grackle_field_data`'s `grid_dx` value to -1 in `pygrackle` since that's what we now recommend when it's not in use (to facilitate the error-check from PR #190).

Fix minor oversight from #190

---

src/python/pygrackle/yt_fields.py

This is in response to a user request on slack. This minor change will allow non-Enzo simulations to use the [yt fields](https://grackle.readthedocs.io/en/latest/Python.html#using-grackle-with-yt) feature of Pygrackle. Currently, we only have a map between simulation parameter names and grackle parameter names for Enzo, but users can still provide them by hand, or at least they could if we didn't raise an exception if a parameter map is not found. This removes the exception and simply prints a warning, allowing the user to proceed.
All of this is fairly undocumented outside of the example Python scripts provided, but I intend to improve that moving forward, but ideally not a part of this pull request.

Allow unsupported simulation types to work with grackle yt fields.

---

src/clib/initialize_chemistry_data.c
src/include/grackle.h
src/python/pygrackle/grackle_defs.pxd
src/python/setup.py

These are macros in the public grackle.h header file. The idea is that external applications will be able to decode the error-codes in a self-consistent manner with the rest of Grackle.
In practice, the main benefit here is that the python bindings no longer need to include a private Grackle header. This will ultimately lead to a minor simplification in GH #208.
Ideally, we would go through and replace all occurences of ``SUCCESS`` with ``GR_SUCCESS`` and ``FAIL`` with ``GR_FAIL`` (so that we can entirely remove ``SUCCESS`` and ``FAIL`` from the codebase), but that would be a fairly invasive change that would touch a lot of code.
- I illustrated what that would look like in ``initialize_chemistry_data.c`` and I also added a compile-time check to ensure consistency of ``GR_SUCCESS`` with …

Introduce GR_SUCCESS and GR_FAIL

---

src/python/pygrackle/grackle_wrapper.pyx

This should let us drop numpy as a build-time requirement. This involved a minor edit to the ``get_field`` c-function written in `grackle_wrapper.pyx` (we now use Cython's built-in typed memory-view functionality instead. While I was there, I made a minor tweak to the function so that it will perform proper error-checking for a plausible failure-mode.
I have not actually modified `setup.py` to remove `numpy` from the list of build-requirements. I quickly tried to do that, but got an opaque setuptools-related error. I decided not to deal with this since we are transitioning to scikit-build-core.

Remove the lone `cimport numpy` line

---

doc/source/Reference.rst
doc/source/Versioning.rst
src/clib/grackle_units.c
src/include/grackle.h

This Introduces a couple tweaks to the documentation (fixing typos and clarifying some confusing topics).
It also modifies the signatures for ``get_temperature_units`` and ``get_velocity_units`` so that the function will accept ``const* code_units`` as an argument. This is ok since the functions don't mutate any of the contents of ``code_units``.

A couple miscellaneous surface-level tweaks

---

doc/source/Integration.rst

While debugging the failing test in #209, I needed to move some declarations around between header files. While doing that I was a little worried about breaking end-user code for anybody who touched these headers. I took care to avoid breaking user-code, but the whole exercise made me realize that there isn't any advantage to telling users about the different headers.
This PR proposes that we Deprecate usage of headers other than than `grackle.h` and `grackle.def`.
- we may still want to expose other headers in the future (when we don't want to include the declaration directly inside `grackle.h` for one reason or another.
- An example of this might be the proposed `grackle_unstable.h` header that provides functions with unstable API. The main purpose is to include debugging functions …

Deprecate usage of headers other than grackle.h and grackle.def

---

README.md

I think this list is a nice way to illustrate how commonly used Grackle is. It could be nice to add this information to the documentation. If we did that, it might be optimal to convert the README from markdown to restructured text to avoid duplicating the list in multiple locations. 
I'm probably missing some cases, but all codes in this initial list provide out-of-the-box support for at least some version of Grackle (and I think they all mention this in their documentation).
One thing to think about is: what is the criterion for inclusion in this list?
- In an ideal world, it would be preferable to exclusively list software that provides out-of-the-box support for Grackle.
- With that said, I don't want to be too exclusive... But the following cases are worth considering:
1. What do we …

add a list of software that uses Grackle to the `README.md` file

---

.circleci/config.yml
src/python/tests/test_initialisation.py

This minimally converts test_initialization to using the gold standard model. This will facilitate tracking of changes to reaction rates coming in PR #177.

Convert reaction rate test to gold standard model

---

src/clib/CMakeLists.txt

Somehow, the list of source files in src/clib/CMakelists.txt had some duplicates in it (maybe when I rebased at one point?). This PR removes the duplicates.

Remove duplicate source files from CMakeLists.txt

---

config/query_version.py

This consists of 2 commits:
1. The first tries to modify the logic for querying git information. This is mostly an attempt to try to address an issue @ChristopherBignamini was encountering.
2. The second commit reformats a bunch of code in order to try to satisfy `flake8` (I also applied `ruff format`)

Fixup query_version.py

---

.circleci/config.yml
CMakeLists.txt
cmake/setup_GTest.cmake
src/clib/c_wrappers/wrap_interpolators_g.c
tests/CMakeLists.txt
tests/unit/CMakeLists.txt
tests/unit/test_unit_interpolators_g.cpp

Hi @mabruzzo, this PR contains the example of Google Test integration (interpolator unit tests) to Grackle main branch we talked about during our latest call.

Example Google Test created

---

.readthedocs.yml

ReadTheDocs has broken CI builds builds unless you explicitly specify that we are building sphinx docs

Fix ReadTheDocs doc CI build

---

src/clib/solve_rate_cool_g.F

This puts the following lines *inside* of the `if (ispecies .gt. 0) then` block:
```
!           return itmask
do i = is+1, ie+1
itmask(i) = itmask_tmp(i)
enddo
```
With `primordial_chemistry=0` these lines were running and setting the itmask to False after the first iteration.
Note: with this fix, newchem-cpp now gives identical results to main for `primordial_chemistry=0`.
@mabruzzo, I'm issuing this as a PR so you can see it as I'm not sure it will affect your transcription. Feel free to merge whenever.

[newchem-cpp] Move itmask reset inside if statement.

---

src/clib/solve_rate_cool_g.F

This is sitting on PR #262. The make_consistent_g function in newchem-cpp was modified to include the D/H ratio when correcting the H densities. However, this should probably not be done if deuterium is not in the network.
With this change, running with `primodial_chemistry=1` produces identical results to main **if the first call to make_consistent_g in solve_rate_cool_g is commented out**. This call was added in this newchem-cpp. Previously make_consistent_g was only called at the end of solve_rate_cool_g. In the future, we will want to change the behavior so that we record initial total species densities at the beginning and then use make_consistent_g to ensure that they are conserved instead of setting them based on constants like the H mass fraction and D/H ratio. The new call to …

[newchem-cpp] Fix deuterium correction in make_consistent

---

.circleci/config.yml
doc/source/Testing.rst
pyproject.toml

This is a very simple PR, where we add some pytest configuration options into pyproject.toml. The main change is that we can now invoke `pytest` from the root of the grackle directory (without passing any arguments). I have updated the CI and docs to reflect this. (Overall, I think this is simpler -- there are fewer considerations for the user).
I also added a few common-sense choices to the pytest configuration (the choices are all documented with comments in `pyproject.toml`). I'm happy to remove them if you don't like them.
I think we should bump the gold standard after this PR is merged

Make `pytest` invokable from the root directory

---

cmake/AddConditionalFortranFlags.cmake
src/clib/cool1d_cloudy_old_tables_g.F
src/clib/initialize_cloudy_data.c
src/clib/initialize_rates.c
src/clib/rate_functions.c
src/example/c_local_example.c

This backports a bunch of minor bugfixes from #273. These are long-standing bugs that result in prominent compiler warnings that are very visible when you use the CMake build-system.[^1] This includes 3 tiny commits:
1. A commit from @ChristopherBignamini that resolved a long-standing bug within `cool1D_cloudy_old_tables_g`
2. A commit removing a relevant flag for the IBM Fortran compiler (from the CMake build system) that existed due to the above bug[^2]
3. A commit that fixes a handful of c functions had a `[-Wreturn-type]` compiler warning where a function was supposed to return a value but had at least 1 control flow branch where we didn't return anything.
While I don't think the bugs actually affected results, I think they should be merged in before the 3.4 release
[^1]: Historically …

Backport some minor bugfixes

---

.circleci/config.yml
tests/CMakeLists.txt
tests/scripts/code_example_checker.py

This PR shifts the core-library tests to a separate "job."
It has come to my attention in recent PRs (e.g. #273, #279), that our current choice to run the core-library test-suite after the Pygrackle test-suite is somewhat undesirable. Specifically, the core-library test-suite is more likely to include unit-tests (while there may not be many unit-tests yet, many forthcoming PRs have proposed adding them).
This is important for 2 reasons:
1. Unit-tests are inherently faster than answer-tests. We should run these as soon as possible so we can fail quickly.
2. Unit-tests are also more specialized than answer-tests. If a unit-test fails, it is likely that an answer-test will also fail. The way things have been configured (before this PR) will cause the answer-test to fail and CI to abort …

CI: shift core-library tests to a separate "job"

---

cmake/setup_GTest.cmake

This makes 2 very minor (but important changes):
1. Most importantly, it tells the googletest build-system not to define "installation rules". Prior to this change, building Grackle with the unit tests would make `cmake --install` install Googletest headers/libraries alongside Grackle headers/libraries (this is unnecessary for using googletest and undesirable).
2. It bumps the default version of googletest that we use from 1.13 to 1.15.2. The build-system included in the newer version has slightly saner defaults. Importantly, Grackle's CMake build-system will no longer print (potentially confusing/concerning) messages about searching for Python.[^1]
I really want to get this merged in before we bump the gold-standard. There is a special streamlined workflow for more easily running all …

2 minor (but important) googletest-related CMake tweaks

---

.circleci/config.yml
cmake/setup_GTest.cmake

Once #295 is merged, we will be ready to update the gold-standard.
This PR makes some anticipated tweaks to the circleci script that have been waiting for this. The tests should be running off of a tag that I pushed to my personal repository.
-----
If everything works out, I imagine we will:
1. merge #295
2. push the new `gold-standard-v3` tag to the main grackle repository
3. review this PR

Circleci tweaks -- from Gold Standard Update

---

src/python/examples/yt_grackle.py
src/python/tests/test_models.py

Prior to this PR,  the `yt_grackle` test-case will fail with an error-message if the ``YT_DATA_DIR`` env variable isn't defined. This PR adds logic to gracefully skip the `yt_grackle` test-case in this scenario (with an explanatory message). This is something that has annoyed me for years.
While I would prefer a more robust solution, I think we should just go with this PR. We can always replace it later if we come up with something better.

tests: gracefully handle `yt_grackle` test-case when `YT_DATA_DIR` isn't defined

---

README.md
doc/source/index.rst

EDIT: This has been modified so that it can be reviewed now.
----------
This is a significant update to the README. The primary impetus for doing this is to emphasize just how easy the new build system is to use![^1]
I also modernized some other parts of the "README" (e.g. added quickstart info, added more links, made some sections a little more concise)
- adding links to various resources at the top of the page.
- slightly tweaking the blurb about Grackle at the top of the page
- Separating the discussion of Features into a separate section and slightly shortening it.[^2]
- I reformatted the list of projects that provide out-of-the-box support for Grackle 
- I added a short section on "getting Grackle." The point is to emphasize how quick and easy this is.
- Addition of a "Getting …

Updating the README

---

doc/source/Python.rst

FYI: I don't care strongly about this PR. I proposed it because I think it's generally a "good idea." If you feel strongly one way or the other, I would be fine with simply closing this PR (but we need to decide one way or the other before 3.4). 
-----
PR #237 proposes an alternative (more robust approach) for managing data file locations (I can go into more detail).  Importantly it provides a standard way to specify a datafile's location across C, C++, Fortran, and Python.
While it is possible to continue supporting `pygrackle.utilities.data_path.grackle_data_dir` (indeed, this is what #237 currently does), we may not want to do that. As a general rule, I think it would be better if we encouraged people to use a single approach across all languages[^1] rather than telling them they can …

Introduce a warning discouraging people from using ``pygrackle.utilities.data_path.grackle_data_dir`` in external code

---

src/clib/CMakeLists.txt
src/clib/Make.config.assemble
src/include/grackle.h
src/include/grackle_chemistry_data.h
src/include/grackle_float.h.in
src/include/grackle_misc.h
src/include/grackle_rate_functions.h
src/include/grackle_types.h
src/python/pygrackle/grackle_defs.pxd

In a prior PR, we deprecated some of the public headers. This PR adds some processor logic to detect when external code includes one of the deprecated headers and warns the person compiling the code (at compile time) that they should just `#include "grackle.h"` instead.
I added some logic to suppress this warning when compiling the core grackle library (I want to fix this, but it will create some merge conflicts with the newchem-cpp branch if we aren't careful). I also tweaked the pygrackle logic so that it only touches `grackle.h`.
I sorta just maintained the status quo with `grackle_rate_functions.h`. It could probably use some attention, but I'm not totally sure what the best way to handle it is...

Warn about usage of deprecated headers

---

src/clib/solve_rate_cool_g.F

This is a redo of PR #286. I have reverted some minor changes in make_consistent and ceiling_species to get the behavior of the newchem-cpp branch as close as we will likely get to main. Ultimately, we will change the behavior of make_consistent to preserve total species densities present before the solve rather than against cosmic constants. The change to ceiling_species is also very minor and could potentially return one day in a more robust way.
Reverting the above will give bitwise identical behavior when `UVBackground=0`. With UV background heating enabled, an extremely subtle divergence creeps in after many sub-cycles. It is related to the application of HI photo-ionization (k24) the HI density or HI photo-heating (piHI) to edot (the change in internal energy). The change is so …

[newchem-cpp] Reverting minor changes to abundance corrections

---

src/example/fortran_example.F
tests/unit/CMakeLists.txt

Last Wednesday, I resolved a few minor problems when we merged in main into newchem-cpp. But 2 minor issues crept by me (that I should have addressed last week):
1. We were missing a line from fortran_example.F (I suspect I deleted the line during the merge)
2. I hadn't realized that the changes from #288 would start producing some warnings in the unit-tests. I fixed this (the commit-message explains why I chose to address it in the way that I did)

[newchem-cpp] 2 minor bugfixes following last week's merge

---

CMakeLists.txt
doc/source/Installation.rst
src/example/CMakeLists.txt
tests/CMakeLists.txt

Must be merged after #304. (the first 5 commits are part of that PR, the last 2 commits are part of this one)
-------
This addresses 2 important configuration scenarios. Specifically, these are ways that I normally don't compile Grackle, but are perfectly reasonable things for users to do. This PR is actually **REALLY IMPORTANT**.
This PR is composed of 2 commits address 2 edge-cases with the build-system:
1. Add a quick fix for when you're building Grackle with single precision.[^1] Prior to this PR, building Grackle as a standalone project with single-precision would produce a compiler error in ``fortran_example.F`` unless you explicitly disable the examples (if you are consuming Grackle as part of a separate project, this wasn't an issue). Now, we disable the Fortran example (I need to …

Address Less Common CMake Configuration Issues

---

.circleci/config.yml

I forgot to make these simplifications to the Continuous Integration in PR #298 (the removed logic is no longer necessary now that we have `gold-standard-v3`)

Circleci simplifications forgotten in PR #298

---

README.md
doc/source/Installation.rst
doc/source/index.rst

This patch primarily consists of 2 changes:
1. A modification to the README (and the duplicated text on the landing page of the website) mentioning Enzo-E as an example of a code with a build system that supports automatically downloading & installing Grackle.
2. The addition of a short paragraph at the top of the Installation page encouraging people to check the documentation of the simulation code that they are using before reading through the entire page. I reference the fact that the build systems of some codes (e.g. Enzo-E) are able to automatically fetch and install Grackle as part of the build process.
I also noticed that the website's landing page had a footnote with missing text. I added the missing text (it duplicates a footnote in the README). While I was doing this, I deleted …

Mention Enzo-E as an example for auto-install

---

cmake/GrackleConfig.cmake.in

This PR fixes a significant bug in **GrackleConfig.cmake** that causes applications with CMake-build systems that expect to link against free-standing installations of Grackle (i.e. Grackle is pre-built) to break when using the newest versions of CMake (version 4.0 or newer).
Background
----------
As part of the installation-process, the CMake build-system installs a file called **GrackleConfig.cmake** alongside the Grackle headers and libraries. This is a special kind CMake script that a build-system searches for and reads when you want to building a downstream application that links against a free-standing Grackle installation. Basically, the script contains queryable metadata about how Grackle was configured and the necessary linker/compilation flags.
While we require version 3.16 of …

[CRITICAL BUGFIX] Fix a significant oversight in **GrackleConfig.cmake**

---

.circleci/config.yml
CMakeLists.txt
src/example/CMakeLists.txt

It has come to my attention  that we are probably going to run out of time on CircleCI this month. This was partially my fault (I had meant to make some adjustments make our workflows more efficient). While doing this, I caught a minor oversight in the CMake-build of the cxx_omp_example.[^1]
I think this should make the PR should reduce the resources used by the CircleCI workflows by ~75%.
It will be easiest to review this commit-by-commit:
1. fix the aforementioned oversight with building `cxx_omp_example`
2. CI: transfer the task of running the OpenMP example from the "test-suite" job to the "corelib-tests"
3. CI: use "small" resource_class for most cases (previously, we defaulted to the "medium" resource_class for every job)
4. CI: Consolidate both jobs running the pygrackle tests
- …

Optimize circleci workflows

---

src/python/pygrackle/utilities/model_tests.py
src/python/tests/test_models.py
src/python/tests/testing_common.py

Prior to this PR, our test suite would fail unless we had an editable install. In reality, all test-cases outside of test_models infer the location of the data files based on the location of the test-files, which are never part of the wheel.[^1] Therefore, this PR introduces a few small tweaks to support testing all test-cases outside of test_models.
Overall, this will be really useful for providing a more rigorous check of the correctness of our precompiled wheels (see PR #320).
[^1]: I know that some packages do ship their test-suites as part of the wheel, but that currently makes absolutely no sense for us unless we provide users with an easy way to get the datafiles. We can always revisit this choice in the future after we merge PRs #235 & #237 (or come up with an equivalent)

Support running subset of pygrackle test without a an editable install

---

src/python/CMakeLists.txt

The line in question was related to passing an `-I/path/to/numpy/headers` (i.e. it specified the directory containing numpy headers) to the C compiler used when compiling  **grackle_wrapper.pyx**. This line hasn't done anything since PR #224 (I simply forgot to remove it)

remove a line that was made obsolete by PR #224

---

pyproject.toml

This is an extremely minor tweak

cython does not need to be a runtime-dependency

---

CMakeLists.txt
cmake/installation_rules.cmake
src/clib/CMakeLists.txt

This is extremely simple and self-explanatory

fix a typo in a CMake variable name

---

pyproject.toml
src/python/CMakeLists.txt

This must be reviewed after PR #330 (it turns out that CI will trigger the bug fixed by that PR when combined with changes in this PR)
----
This PR swaps out our custom handling of compiling cython files (when compiling pygrackle) to using the [cython-cmake package](https://pypi.org/project/cython-cmake/). This package is maintained by the scikit-build-core people.
Essentially, the main benefit of doing this is achieving better dependency tracking. This comes up with incremental rebuilds.
If you install pygrackle with:
```sh
pip install --no-build-isolation -Cbuild-dir=pygrackle-build -ve.
```
you are essentially putting intermediate build-artifacts into a directory called **pygrackle-build**. If you make a tweak to a grackle source file, you can invoke the command again and the build …

Tweak  cython-handling in build-system

---

.github/CODE_OF_CONDUCT.md

I was deleting some old branches and realized that I never made a PR for this branch.
------------
By adding this file, GitHub adds a nicely labeled tab when you scroll down to the README
Numpy and Scipy both do something similar (but I'm honestly not sure where the file that does this is in the Numpy repository)
To see this change, go to [my branch with this change](https://github.com/mabruzzo/grackle/tree/code-of-conduct-redirect?tab=readme-ov-file) and you will be able to see a "Code of conduct" tab between the "README" tab and the "License" tab

Use builtin GitHub feature to nicely redirect to Code of Conduct

---

doc/source/Contributing.rst
doc/source/Installation.rst
doc/source/Integration.rst
doc/source/Interaction.rst
doc/source/Parameters.rst
doc/source/Python.rst
doc/source/Reference.rst
doc/source/Testing.rst
doc/source/Versioning.rst

This is **EXTREMELY** simple: we simply removed spurious indentations from documentation to fix rendering of documentation. <span style="color:red;">Importantly, no text has been edited.</span>
In more detail, the reStructuredText Markup Specification [notes that](https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#toc-entry-26) all indented blocks of text (without preceding markup) as quote-blocks. There were many chunks blocks of text that unintentionally met this definition (it is common in lists)
The impetus for this change is our transition to the new "Furo" sphinx-theme since Furo applied special formatting to quote-blocks (the older themes did not do this). The collapsible section illustrates a before-and-after of how this affects rendered text:
<details> …

Remove spurious indentations (fix rendering of text)

---

.circleci/config.yml
.readthedocs.yml
doc/source/Python.rst
doc/source/requirements.txt
pyproject.toml

This adjusts the machinery for installing development dependencies. (it supersedes #301). This does **not** need a gold-standard update.
Previously, we were specifying the development dependencies as optional-dependencies (commonly called "extras"). "Extras" are fundamentally intended to specify optional runtime dependencies of a python package (e.g. the way that installing `h5py` "unlocks" extra functionality in `yt`). While this has historically been a common way to do things, it had fundamental flaws:
1. You can't actually install these dependencies without installing the package itself. This is a minor inconvenience in 2 scenarios:
- there are times, especially with documentation/linters/type-checking where you want dev dependencies without installing the package itself
- if you've …

Dependency group

---

src/python/examples/cooling_cell.py
src/python/examples/cooling_rate.py
src/python/examples/freefall.py
src/python/examples/yt_grackle.py
src/python/pygrackle/utilities/model_tests.py
src/python/pygrackle/utilities/testing.py
src/python/tests/test_models.py

We talked about this last week. This tweaks `src/python/examples/*.py` and `src/python/tests/test_models.py` so that we avoid using subprocess (and directly import code instead).
On my machine, this shaves ~22 seconds off of the tests (i.e. ~20% of the runtime)

[newchem-cpp] Speedup test_models.py by direct importing

---

doc/source/Python.rst

For the embedded pygrackle build:
- I tried to make the existing documentation a little more clear
- I tried to make it more clear how you might resolve issues when the build-system can't locate the HDF5 library (99% of the time, this should not be a problem)
- I also tried to make it clear how you might customize the build of the core grackle library (that occurs as part of the pygrackle build)

Add more detail to pygrackle build documentation

---

.github/dependabot.yml
.github/workflows/wheels.yml
pyproject.toml
scripts/configure_file.py
scripts/wheels/README.md
scripts/wheels/binary_license_annex.txt.in
scripts/wheels/check_packaged_dependency_licenses.py
scripts/wheels/cibw_before_build.py
scripts/wheels/cibw_test_command.sh
scripts/wheels/zlib_license_for_macos.txt
src/python/tests/test_get_grackle_version.py

EDIT: This is ready to go
> [!NOTE]
> The large number of changed lines is misleading. Most of the lines are for the licenses that are bundled with the wheels (since the binary wheels uploaded to PyPI need to include some shared libraries)
----------
This PR set up the continuous integration to test creation and uploading of wheels.
Here is the [test.pypi page for pygrackle](https://test.pypi.org/project/pygrackle/). 
You can try installing pygrackle from PyPI by invoking
```sh
pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ pygrackle
```
We are going to need to do a followup PR after this one (I want to test uploading to test.pypi from the main grackle repository before uploading a wheel to pypi).
----------
It might be useful to refactor …

Packaging Pygrackle

---

pyproject.toml

This is really minor... Basically both PRs added a field to pyproject.toml that mentioning the README, but they did it in entirely different ways. As a result, we were effectively defining the location of the README twice (which pip does **NOT** like)

fixing a bug in pyproject.toml that arose because PRs #320 and #350 introduced conflicting changes

---

.circleci/config.yml
src/clib/calc_temp_cloudy_g.F
src/python/tests/test_get_grackle_version.py

Fixes #366. This change requires a gold-standard bump.
EDIT: There was a minor bug with the way that **test_get_grackle_version.py** handled tags starting with `gold-standard-v*`. I back-ported a fix that I had previously applied to the `newchem-cpp` branch.
EDIT2: I had to reorder commits (and alter the commit associated with the "gold-standard-v4") so that the fix to **test_get_grackle_version.py** is actually present when we check out "gold-standard-v4"

address a bug calc_temp_cloudy_g.F

---

.github/workflows/wheels.yml

I had forgotten that we needed to do before closing PR #388
Once I realized it, I decided to do one final test-upload to testpypi (I temporarily pushed the `grackle-3.4.1-dev` tag) and while I was at it, I merged in #373 (which bumped the versions of software used in the workflow).
Once the test-upload succeeds, I'll merge in this branch and perform the actual release (and I'll delete the grackle-3.4.1-dev tag)

Tweaking wheels.yml for release to PyPI

---

src/python/tests/test_get_grackle_version.py

Essentially, a bug made the test fail if you ran the test and you had checked out the commit associated with the tag of the most recent grackle version number.

Fix a bug in test_get_grackle_version.py

---

.circleci/config.yml
pyproject.toml
src/python/setup.cfg

There are **NO** prerequisites for reviewing/merging this PR
------------
Background
----------
Previously we had replaced 99% uses of the Flake8 linter with the Ruff linter (not to be confused with the Ruff formatter). We had continued to use the Flake8 linter to deal with the following 2 files:
1. **gracklepy/utilities/testing.py**
2. **gracklepy/__init__.py**
In more detail, we were suppressing certain warnings in these 2 files from Flake8, and transistioning to using the Ruff formatter for these files would involve making a few changes.
More recently PRs #368 and #369 introduced the required changes into the main branch. Now that those changes have been ported to the newchem-cpp branch, we are able to make this change.
What Changed
------------
I essentially changed 3 things:
1. We no …

[newchem-cpp] Remove last references to `Flake8`

---

src/python/tests/test_models.py

This patch replaces `os.rename` in **test_models.py** with the `shutil.move` function.
This patch addresses a bug that can arise when we run the answer-tests store-mode. Specifically, this bug arises when running the python example scripts (executed by **test_models.py**). These examples always write a temporary file with the result of the calculation. When run in store mode, the testing system moves the temporary file into the answer directory.
Prior to this patch, we used `os.rename` to move the temporary file. Unfortunately, this produces an error when the temporary file and the answer directory are located on separate filesystems. By replacing `os.rename` with `shutil.move` we can eliminate this issue.
While the scenario we are addressing may sound somewhat pathological, it's actually …

test bugfix: use `shutil.move` in test_models.py

---

src/clib/CMakeLists.txt
src/clib/auto_general.c.in
src/clib/auto_general.h
src/clib/initialize_UVbackground_data.c
src/clib/initialize_UVbackground_data.h
src/clib/initialize_chemistry_data.c
src/clib/initialize_cloudy_data.c
src/clib/initialize_cloudy_data.h
src/clib/initialize_dust_yields.h
src/clib/initialize_metal_chemistry_rates.h
src/clib/initialize_rates.c
src/clib/initialize_rates.h

This can be reviewed at any time (there are no dependencies).
-------------
This PR introduces internal header files that holds declarations of various initialization and cleanup routines.
The benefits of this PR are 2-fold:
1. This is considered a better practice than just copying and pasting the forward declarations around. By including the header where we declare the function in the file where we define the function, the compiler is able to ensure that the declaration and definition are compatible, which is especially useful if we need to introduce changes. (We have to manually ensure compatibility if we just copy and paste).
2. This is an important step to converting these files to C++, which is a crucial step on the path to transcribing `lookup_cool_rates1d_g` (strictly speaking, it …

[newchem-cpp] Introduce internal `initialize_*.h` and `auto_general.h` headers

---

.circleci/config.yml

This updates the newchem-cpp gold standard to version 6 after merging PR #405.

[newchem-cpp] Update to gold standard v6
